In [14]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv('/content/1.02.+Multiple+linear+regression (1).csv')

In [4]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [5]:
data.describe(include='all')

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [12]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [15]:
reg = LinearRegression()

In [16]:
reg.fit(x, y)

LinearRegression()

In [17]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [18]:
reg.intercept_

0.29603261264909486

In [19]:
reg.score(x, y)

0.4066811952814283

In [20]:
x.shape

(84, 2)

In [21]:
r2 = reg.score(x, y)

n = x.shape[0]

p = x.shape[1]

adjusted_r2 = 1 - (1-r2)*(n-1)/(n-p-1)

In [22]:
adjusted_r2

0.3920313482513401

In [24]:
from sklearn.feature_selection import f_regression

In [25]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [26]:
p_values = f_regression(x, y)[1]

In [27]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [29]:
p_values.round(3)

array([0.   , 0.676])

In [32]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])

In [33]:
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [34]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [35]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [39]:
data_real = pd.read_csv('/content/real_estate_price_size_year (1).csv')

In [40]:
data_real.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [41]:
data_real.describe(include='all')

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [42]:
x = data_real[['size', 'year']]
y = data_real['price']

In [43]:
reg_real = LinearRegression()

In [46]:
reg_real.fit(x, y)

LinearRegression()

In [47]:
reg_real.intercept_

-5772267.017463279

In [48]:
reg_real.coef_

array([ 227.70085401, 2916.78532684])

In [50]:
reg_real.score(x, y)

0.7764803683276795

In [52]:
x.shape

(100, 2)

In [54]:
r2 = reg_real.score(x, y)

n = x.shape[0]

p = x.shape[1]

adjusted_r2 = 1 - (1-r2)*(n-1)/(n-p-1)

In [55]:
adjusted_r2

0.7718717161282502

In [56]:
f_regression(x, y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [57]:
p_values = f_regression(x, y)[1]

p_values

p_values.round(3)

array([0.   , 0.357])

In [59]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0     size
1     year

In [62]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

reg_summary

Features  Coefficients  p-values
0     size      0.001654     0.000
1     year     -0.008270     0.357