In [140]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [141]:
data = pd.read_csv('/content/1.02.+Multiple+linear+regression (2).csv')

In [142]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [143]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [144]:
from sklearn.preprocessing import StandardScaler

In [145]:
scaler = StandardScaler()

In [146]:
scaler.fit(x)

StandardScaler()

In [147]:
x_scaled = scaler.transform(x)

In [148]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [149]:
reg = LinearRegression()

In [150]:
reg.fit(x_scaled, y)

LinearRegression()

In [151]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [152]:
reg.intercept_

3.330238095238095

In [153]:
reg_summary = pd.DataFrame([['Bias'], ["SAT"], ['Rand 1,2,3']],
                            columns=["Features"])

reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [154]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [155]:
new_data = pd.DataFrame([[1700, 2], [1800, 1]], columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [156]:
reg.predict(new_data)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [157]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [158]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [159]:
reg_simple = LinearRegression()

x_simple_matrix = x_scaled[:,0].reshape(-1, 1)

x_simple_matrix

array([[-1.26338288],
       [-1.74458431],
       [-0.82067757],
       [-1.54247971],
       [-1.46548748],
       [-1.68684014],
       [-0.78218146],
       [-0.78218146],
       [-0.51270866],
       [ 0.04548499],
       [-1.06127829],
       [-0.67631715],
       [-1.06127829],
       [-1.28263094],
       [-0.6955652 ],
       [ 0.25721362],
       [-0.86879772],
       [-1.64834403],
       [-0.03150724],
       [-0.57045283],
       [-0.81105355],
       [-1.18639066],
       [-1.75420834],
       [-1.52323165],
       [ 1.23886453],
       [-0.18549169],
       [-0.5608288 ],
       [-0.23361183],
       [ 1.68156984],
       [-0.4934606 ],
       [-0.73406132],
       [ 0.85390339],
       [-0.67631715],
       [ 0.09360513],
       [ 0.33420585],
       [ 0.03586096],
       [-0.35872421],
       [ 1.04638396],
       [-0.65706909],
       [-0.13737155],
       [ 0.18984542],
       [ 0.04548499],
       [ 1.1618723 ],
       [-1.37887123],
       [ 1.39284898],
       [ 0

In [160]:
reg_simple.fit(x_simple_matrix , y)

LinearRegression()

In [161]:
reg_simple.predict(new_data_scaled[:, 0].reshape(-1, 1))

array([3.08970998, 3.25527879])

In [162]:
data_real = pd.read_csv('/content/real_estate_price_size_year (1).csv')

In [163]:
data_real.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [164]:
data_real.describe(include='all')

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [165]:
X = data_real[['size', 'year']]
y = data_real['price']

In [166]:
scaler_real = StandardScaler()

In [167]:
scaler_real.fit(X)

StandardScaler()

In [168]:
x_scaled_real = scaler_real.transform(X)

In [169]:
reg_real = LinearRegression()

In [170]:
reg_real.fit(x_scaled_real, y)

LinearRegression()

In [171]:
reg_real.coef_

array([67501.57614152, 13724.39708231])

In [172]:
reg_real.intercept_

292289.4701599997

In [173]:
reg_summary_real = pd.DataFrame([['Bias'], ["size"], ['year']],
                            columns=["Features"])

reg_summary_real['Weights'] = reg_real.intercept_, reg_real.coef_[0], reg_real.coef_[1]

In [174]:
reg_summary_real

Features        Weights
0     Bias  292289.470160
1     size   67501.576142
2     year   13724.397082

In [175]:
new_data_real = pd.DataFrame([[643.09, 2015], [656.22, 2009]], columns=['size', 'year'])

new_data_real

size  year
0  643.09  2015
1  656.22  2009

In [176]:
reg_real.predict(new_data_real)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([71356538.19186236, 72160487.50410669])

In [177]:
new_data_scaled = scaler_real.transform(new_data_real)
new_data_scaled

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206]])

In [178]:
reg_real.predict(new_data_scaled)

array([251487.55831903, 236976.55857112])

In [179]:
reg_simple_real = LinearRegression()

x_simple_matrix = x_scaled_real[:,0].reshape(-1, 1)

x_simple_matrix

array([[-0.70816415],
       [-0.66387316],
       [-1.23371919],
       [ 2.19844528],
       [ 1.42498884],
       [-0.937209  ],
       [-0.95171405],
       [-0.78328682],
       [-0.57603328],
       [-0.53467702],
       [ 0.69939906],
       [ 3.33780001],
       [-0.53467702],
       [ 0.52699137],
       [ 1.51100715],
       [ 1.77668568],
       [-0.54810263],
       [-0.77276222],
       [-0.58004747],
       [ 0.58943055],
       [-0.78365788],
       [-1.02322731],
       [ 1.19557293],
       [-1.12884431],
       [-1.10378093],
       [ 0.84424715],
       [-0.95171405],
       [ 1.62279723],
       [-0.58004747],
       [ 2.17014356],
       [ 0.5306345 ],
       [-0.58004747],
       [-0.8606021 ],
       [-1.10378093],
       [ 0.015233  ],
       [-0.77603429],
       [-0.10057126],
       [-0.95387294],
       [-0.56517136],
       [-0.5219598 ],
       [ 0.56983186],
       [-0.57603328],
       [-0.10057126],
       [ 1.62279723],
       [ 0.69939906],
       [-0

In [180]:
reg_simple_real.fit(x_simple_matrix , y)

LinearRegression()

In [181]:
reg_simple_real.predict(new_data_scaled[:, 0].reshape(-1, 1))

array([245436.6193764 , 248366.95626666])